version: '3'
services:
  es01:
    restart: always
    image: ccc
    container_name: tes01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  es02:
    restart: always
    image: ccc
    container_name: tes02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet
  fscrawler:
    restart: always
    container_name: fscrawler
    image: openjdk
    depends_on:
      - es01
      - es02

    working_dir: /fscrawler-es7-2.7
    #    entrypoint: sh entrypoint.sh
    volumes:
      - ./Fscrawler/fscrawler-es7-2.7-SNAPSHOT:/fscrawler-es7-2.7
      - ./Fscrawler/config:/fscrawler-es7-2.7/config
      - /Fscrawler/fscrawler-es7-2.7/data:/tmp/es
        #- ./data:/fscrawler-es7-2.7/data
        #- ./entrypoint.sh:/fscrawler-es7-2.7/entrypoint.sh
    ports: 
      - 8081:8081
    networks:
      - esnet
    command: /fscrawler-es7-2.7/bin/fscrawler --config_dir /fscrawler-es7-2.7/config  job_name --loop 0 --rest


       
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  
networks:
  esnet:
